bot:
  token: ""
  debug: true
  timeout: 30
activePenalties:
  - mute
managed:
  chats:
    - -1001636555309
  user: 5129190705
limits:
  kick:
      day: 1000
      hour: 20
      minute: 5
  mute:
      day: 1000
      hour: 20
      minute: 5
thresholds:
  kick:
      day: 100
      hour: 5
      minute: 2
  mute:
      day: 100
      hour: 5
      minute: 2
penalties:
  kick:
      day: 1440
      hour: 60
      minute: 5
  mute:
      day: 1440
      hour: 60
      minute: 5